### ISSUE TITLE
Image metadata is being displayed as broken even though it is correctly validated through hash

### ISSUE THREAD

**Issue by tehnalogos** [lukso-network/universalprofile.cloud#459]
<img width="940" alt="Screenshot 2024-09-16 at 3 41 13 PM" src="https://github.com/user-attachments/assets/16b5bb8a-646a-4986-bce3-980131a7b356">

https://universalprofile.cloud/0xec1c59e78de6f840a66b6ee8e4066700be863529?assetGroup=collectibles

**Comment by dzbo** [comment]
Hey @tehnalogos thanks for report, but please use official Discord channel to report any feedback, thanks!
